export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_RESET = "ORDER_RESET";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const MY_ORDER_LIST_REQUEST = "MY_ORDER_LIST_REQUEST";
export const MY_ORDER_LIST_SUCCESS = "MY_ORDER_LIST_SUCCESS";
export const MY_ORDER_LIST_FAIL = "MY_ORDER_LIST_FAIL";

export const ALL_ORDER_LIST_REQUEST = "ALL_ORDER_LIST_REQUEST";
export const ALL_ORDER_LIST_SUCCESS = "ALL_ORDER_LIST_SUCCESS";
export const ALL_ORDER_LIST_FAIL = "ALL_ORDER_LIST_FAIL";

export const NOT_ACCEPTED_ORDER_COUNT_REQ = "NOT_ACCEPTED_ORDER_COUNT_REQ";
export const NOT_ACCEPTED_ORDER_COUNT_SUCCESS =
  "NOT_ACCEPTED_ORDER_COUNT_SUCCESS";
export const NOT_ACCEPTED_ORDER_COUNT_FAIL = "NOT_ACCEPTED_ORDER_COUNT_FAIL";
